// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Transition: typeof import('./../components/common/Transition.vue')['default']
    UPopup: typeof import('./../components/common/UPopup.vue')['default']
    UTabs: typeof import('./../components/common/UTabs/index.vue')['default']
  }
}

export {}
